name: Acessar Página Web

on:
  push:
    branches:
      - vinicius  # Ou a branch que você preferir

jobs:
  access-page:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      
    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Escolha a versão do Node.js que deseja usar

    - name: Instalar dependências
      run: npm install

    - name: Executar script Node.js
      run: node acessar_paginas.js
