on:
  workflow_dispatch:
jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo content
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: npm

      - name: Install dependencies
        run: npm install octokit

      - name: Generate token
        id: generate_token
        uses: tibdex/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
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: Run script
        run: |
          node acessar_paginas.js
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}